"use client";
import{useMemo,useState}from"react";
import{BarChart3,BookOpen,Box,Check,Eye,FileText,LogOut,MousePointerClick,Server,Settings,Trash2,UploadCloud}from"lucide-react";
import type{ContentRow}from"@/lib/content";

const sections=[{key:"dashboard",label:"Kontrol Paneli",icon:BarChart3},{key:"mods",label:"Mod Yönetimi",icon:Box},{key:"journals",label:"Oyun Günlüğü",icon:BookOpen},{key:"servers",label:"Sunucu Yönetimi",icon:Server},{key:"own_server",label:"Kendi Sunucum",icon:Server},{key:"applications",label:"Sunucu Başvuruları",icon:Check},{key:"pages",label:"Kurumsal Sayfalar",icon:FileText},{key:"analytics",label:"İstatistikler",icon:Eye},{key:"settings",label:"Site Ayarları",icon:Settings}] as const;

export default function AdminPanel({user,signout,initial,analytics,settings}:{user:string;
signout:string;
initial:Record<string,ContentRow[]>;
analytics:any[];
settings:Record<string,string>}){const[active,setActive]=useState("dashboard"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
const views=useMemo(()=>analytics.filter(x=>x.event==="view").reduce((n,x)=>n+Number(x.count),0),[analytics]),downloads=useMemo(()=>analytics.filter(x=>x.event==="download").reduce((n,x)=>n+Number(x.count),0),[analytics]);
async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();
setBusy(true);
const form=e.currentTarget;
const fd=new FormData(form);
if(active==="settings"){for(const key of ["adsense_enabled","adsense_auto_ads"])if(!fd.has(key))fd.set(key,"");}
fd.set("section",active==="own_server"?"servers":active==="pages"?"settings":active);
if(active==="own_server")fd.set("featured","true");
const r=await fetch("/api/admin/content",{method:"POST",body:fd}),j=await r.json();
setMessage(r.ok?"Kaydedildi ✓":j.error||"Kaydedilemedi");
setBusy(false);
if(r.ok&&!["settings","pages"].includes(active))form.reset()}async function approve(id:number){const r=await fetch("/api/admin/content",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,section:"servers",op:"approve"})});
if(r.ok)location.reload()}async function remove(id:number,section:string){if(!confirm("Bu içerik silinsin mi?"))return;
const r=await fetch("/api/admin/content",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,section,op:"delete"})});
if(r.ok)location.reload()}const input="admin-input";
const cards=[{t:"Toplam görüntülenme",v:views,i:Eye},{t:"İndirme tıklaması",v:downloads,i:MousePointerClick},{t:"Yayınlanan mod",v:initial.mods.length,i:Box},{t:"Sunucu",v:initial.servers.length,i:Server}];
return <main className="min-h-screen p-4 sm:p-7"><div className="mx-auto max-w-7xl"><header className="mb-7 flex items-center justify-between gap-4"><div><p className="eyebrow">YÖNETİM MERKEZİ</p><h1 className="text-3xl font-black">Admin Paneli</h1><p className="text-zinc-500">{user}</p></div><form method="post" action={signout}><button className="admin-secondary"><LogOut size={17}/>Çıkış</button></form></header><div className="grid gap-6 lg:grid-cols-[240px_1fr]"><aside className="admin-box h-fit p-3">{sections.map(({key,label,icon:Icon})=><button key={key} onClick={()=>{setActive(key);
setMessage("")}} className={`admin-nav ${active===key?"active":""}`}><Icon size={18}/>{label}</button>)}</aside><section className="admin-box min-w-0 p-5 sm:p-7">{active==="dashboard"&&<div><h2 className="text-2xl font-black">Genel Bakış</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({t,v,i:Icon})=><div className="stat-card" key={t}><Icon/><span>{t}</span><b>{v}</b></div>)}</div><p className="mt-7 rounded-xl border border-violet-400/20 bg-violet-500/10 p-4 text-zinc-300">Ziyaretçi gizliliği korunur. İstatistikler toplu tutulur;
 tam IP adresi veya kişisel cihaz dosyası oluşturulmaz.</p></div>}
{active==="pages"&&<form onSubmit={submit} className="grid gap-6"><div><p className="eyebrow">ADSENSE İÇİN GEREKLİ SAYFALAR</p><h2 className="mt-2 text-2xl font-black">Kurumsal Sayfalar</h2><p className="mt-2 text-zinc-400">Hakkımızda, Gizlilik Politikası ve İletişim sayfalarının içeriklerini buradan düzenleyebilirsin.</p></div><div className="settings-section"><h3>Hakkımızda</h3><label>Sayfa başlığı<input name="about_title" defaultValue={settings.about_title||"Hakkımızda"} className={input}/></label><label>Sayfa metni<textarea name="about_content" defaultValue={settings.about_content||"Ali Ulubaş Bedrock Merkezi; Minecraft Bedrock oyuncuları için modları, sunucu tanıtımlarını ve oyun deneyimlerini tek yerde buluşturan bağımsız bir içerik platformudur.\n\nAmacımız, oyuncuların işine yarayan içerikleri anlaşılır biçimde sunmak ve kaliteli Minecraft topluluklarının daha fazla oyuncuya ulaşmasına yardımcı olmaktır."} className={input} rows={7}/></label></div><div className="settings-section"><h3>Gizlilik Politikası</h3><label>Sayfa başlığı<input name="privacy_title" defaultValue={settings.privacy_title||"Gizlilik Politikası"} className={input}/></label><label>Politika metni<textarea name="privacy_content" defaultValue={settings.privacy_content||"Bu site, ziyaretçi deneyimini geliştirmek ve toplu kullanım istatistikleri oluşturmak amacıyla sınırlı teknik veriler işleyebilir. İletişim veya sunucu başvuru formları üzerinden gönderdiğiniz bilgiler yalnızca talebinizi değerlendirmek için kullanılır.\n\nSitede Google AdSense gibi üçüncü taraf reklam hizmetleri kullanılabilir. Bu hizmetler, ilgi alanlarına uygun reklamlar sunmak için çerezlerden yararlanabilir. Çerez tercihlerinizi tarayıcınızdan yönetebilirsiniz.\n\nKişisel bilgiler izinsiz olarak satılmaz. Yasal zorunluluklar dışında üçüncü kişilerle paylaşılmaz."} className={input} rows={10}/></label></div><div className="settings-section"><h3>İletişim</h3><div className="grid gap-4 sm:grid-cols-2"><label>Sayfa başlığı<input name="contact_title" defaultValue={settings.contact_title||"İletişim"} className={input}/></label><label>Gmail adresi<input type="email" name="contact_email" defaultValue={settings.contact_email||"aliulubasbusien@gmail.com"} className={input}/></label></div><label>Açıklama<textarea name="contact_content" defaultValue={settings.contact_content||"İş birliği, reklam, sunucu tanıtımı ve siteyle ilgili sorularınız için aşağıdaki kanallardan iletişime geçebilirsiniz."} className={input} rows={4}/></label><div className="grid gap-4 sm:grid-cols-3"><label>YouTube<input name="youtube" defaultValue={settings.youtube||"aliulubas20"} className={input}/></label><label>TikTok<input name="tiktok" defaultValue={settings.tiktok||"aliulubas20"} className={input}/></label><label>Instagram<input name="instagram" defaultValue={settings.instagram||"aliulubas20"} className={input}/></label></div></div><button disabled={busy} className="admin-primary">Üç Sayfayı Kaydet ve Yayınla</button></form>}
{active==="analytics"&&<div><h2 className="text-2xl font-black">İstatistikler</h2><div className="mt-5 overflow-x-auto"><table className="stats-table"><thead><tr><th>Tarih</th><th>Sayfa</th><th>İşlem</th><th>Cihaz</th><th>Tarayıcı</th><th>Sayı</th></tr></thead><tbody>{analytics.map((x,i)=><tr key={i}><td>{x.day}</td><td>{x.path}</td><td>{x.event}</td><td>{x.device}</td><td>{x.browser}</td><td>{x.count}</td></tr>)}</tbody></table></div></div>}{["mods","journals","servers","own_server"].includes(active)&&<div><h2 className="text-2xl font-black">{active==="mods"?"Mod Ekle":active==="journals"?"Günlük Paylaş":active==="own_server"?"Kendi Sunucumu Düzenle":"Sunucu Ekle"}</h2><form onSubmit={submit} className="mt-5 grid gap-5"><div className="grid gap-4 sm:grid-cols-2"><label>Başlık<input required name="title" className={input}/></label>{active!=="journals"&&<label>Sürüm<input required name="version" className={input}/></label>}{(active==="servers"||active==="own_server")&&<><label>Sunucu türü<select name="edition" className={input}><option>Java & Bedrock</option><option>Sadece Bedrock</option><option>Sadece Java</option></select></label><label>IP / Adres<input required name="address" className={input}/></label><label>Port<input name="port" className={input} placeholder="19132"/></label></>}</div><label>Açıklama<textarea required name="description" className={input} rows={5}/></label><label className="upload-zone"><UploadCloud/><b>{active==="journals"?"Görsel veya video":"Kapak görseli"}</b><input required type="file" name="image" accept={active==="journals"?"image/*,video/*":"image/*"}/></label>{active==="mods"&&<label className="upload-zone"><UploadCloud/><b>İndirilecek mod dosyası</b><input required type="file" name="download" accept=".mcpack,.mcaddon,.zip"/></label>}{(active==="servers"||active==="own_server")&&<label className="upload-zone"><UploadCloud/><b>En fazla 5 sunucu içi görsel</b><input type="file" multiple name="gallery" accept="image/*"/></label>}<button disabled={busy} className="admin-primary">{busy?"Yükleniyor...":"Kaydet ve Yayınla"}</button></form><div className="mt-8 grid gap-3">{(active==="own_server"?initial.servers.filter(x=>x.status==="featured"):initial[active].filter(x=>active!=="servers"||x.status==="approved")).map(x=><div className="request-row" key={x.id}><div><b>{x.title}</b><p>{x.version||x.edition||"İçerik"}</p></div><button onClick={()=>remove(x.id,active==="own_server"?"servers":active)} className="icon-button bad"><Trash2/></button></div>)}</div></div>}
{active==="applications"&&<div><p className="eyebrow">BEKLEYENLER</p><h2 className="mt-2 text-2xl font-black">Sunucu Başvuruları</h2><div className="mt-5 grid gap-4">{initial.servers.filter(x=>x.status==="pending").map(x=><article className="application-card" key={x.id}><div className="flex flex-wrap items-start justify-between gap-3"><div><h3>{x.title}</h3><p>{x.edition} · {x.version} · {x.address}{x.port?":"+x.port:""}</p></div><span>Onay bekliyor</span></div><div className="application-grid"><p><b>Başvuran:</b> {x.owner_name}</p><p><b>İletişim:</b> {x.contact}</p><p><b>Ödemeyi gönderen:</b> {x.payment_sender}</p><p><b>Ödeme açıklaması:</b> {x.payment_note}</p><p><b>Ödenen tutar:</b> {x.payment_amount||0} TL</p><p><b>Yayın süresi:</b> {x.duration_days||0} gün</p></div>{x.private_note&&<div className="private-note"><b>Sana özel mesaj</b><p>{x.private_note}</p></div>}<p className="mt-3 text-zinc-300">{x.description}</p><div className="mt-4 flex gap-2"><button onClick={()=>approve(x.id)} className="admin-primary"><Check size={17}/>Onayla ve Yayınla</button><button onClick={()=>remove(x.id,"servers")} className="admin-secondary text-red-400"><Trash2 size={17}/>Sil</button></div></article>)}{!initial.servers.some(x=>x.status==="pending")&&<p className="text-zinc-500">Bekleyen sunucu başvurusu yok.</p>}</div></div>}
{active==="settings"&&<form onSubmit={submit} className="grid gap-6"><div><p className="eyebrow">GENEL AYARLAR</p><h2 className="mt-2 text-2xl font-black">Site Ayarları</h2></div><div className="settings-section"><div><p className="eyebrow">ÖDEME BİLGİLERİ</p><h3>Sunucu reklam ödemesi</h3><p>Bu bilgiler Sunucu Ekle sayfasında ziyaretçilere gösterilir.</p></div><div className="grid gap-4 sm:grid-cols-2"><label>IBAN<input name="payment_iban" defaultValue={settings.payment_iban||""} className={input} placeholder="TR00 0000 0000 0000 0000 0000 00"/></label><label>Alıcı adı soyadı<input name="payment_recipient" defaultValue={settings.payment_recipient||""} className={input}/></label><label>Sunucu reklam ücreti<input name="server_ad_price" defaultValue={settings.server_ad_price||""} className={input} placeholder="Örnek: 250 TL"/></label></div><label>Ödeme talimatı<textarea name="payment_instructions" defaultValue={settings.payment_instructions||"Havale açıklamasına sunucu adınızı yazın."} className={input} rows={3}/></label></div><div className="grid gap-4 sm:grid-cols-2"><label>Site adı<input name="site_name" defaultValue={settings.site_name||"ALİ ULUBAŞ"} className={input}/></label><label>Ana başlık<input name="hero_title" defaultValue={settings.hero_title||"Modları keşfet, sunuculara katıl, oyun macerama ortak ol."} className={input}/></label><label>YouTube kullanıcı adı<input name="youtube" defaultValue={settings.youtube||"aliulubas20"} className={input}/></label><label>TikTok kullanıcı adı<input name="tiktok" defaultValue={settings.tiktok||"aliulubas20"} className={input}/></label><label>Instagram kullanıcı adı<input name="instagram" defaultValue={settings.instagram||"aliulubas20"} className={input}/></label></div><label>Site açıklaması<textarea name="site_description" defaultValue={settings.site_description||"Bedrock modları, seçilmiş Minecraft sunucuları ve oyun dünyamdan en yeni paylaşımlar burada."} className={input} rows={4}/></label><div className="settings-section"><div><p className="eyebrow">GOOGLE ADSENSE</p><h3>Reklam Ayarları</h3><p>AdSense hesabındaki yayıncı kimliği ve reklam birimi numaralarını gir.</p></div><label className="toggle-line"><input type="checkbox" name="adsense_enabled" defaultChecked={settings.adsense_enabled==="on"}/><span>Reklamları sitede etkinleştir</span></label><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2">AdSense kodunu yapıştır<textarea name="adsense_code" defaultValue={settings.adsense_code||""} className={input} rows={6} placeholder="<script ...> veya <ins class=&quot;
adsbygoogle&quot;
 ...> kodunu buraya yapıştır"/></label><label>Yayıncı kimliği<input name="adsense_client" defaultValue={settings.adsense_client||""} className={input} placeholder="ca-pub-1234567890"/></label><label>Reklam biçimi<select name="adsense_format" defaultValue={settings.adsense_format||"auto"} className={input}><option value="auto">Otomatik</option><option value="rectangle">Dikdörtgen</option><option value="horizontal">Yatay</option><option value="vertical">Dikey</option></select></label><label>Ana sayfa reklam birimi<input name="adsense_home_slot" defaultValue={settings.adsense_home_slot||""} className={input} placeholder="1234567890"/></label><label>Liste sayfası reklam birimi<input name="adsense_list_slot" defaultValue={settings.adsense_list_slot||""} className={input} placeholder="1234567890"/></label><label>Detay sayfası reklam birimi<input name="adsense_detail_slot" defaultValue={settings.adsense_detail_slot||""} className={input} placeholder="1234567890"/></label><label className="toggle-line mt-6"><input type="checkbox" name="adsense_auto_ads" defaultChecked={settings.adsense_auto_ads==="on"}/><span>Otomatik reklamları kullan</span></label></div><div className="adsense-status"><b>{settings.adsense_client?"AdSense kimliği kayıtlı ✓":"AdSense henüz bağlanmadı"}</b><span>Reklamların görünmesi için Google onayı ve geçerli reklam birimleri gerekir.</span></div></div><div className="settings-section"><div><p className="eyebrow">ARAMA MOTORLARI</p><h3>SEO Ayarları</h3></div><div className="grid gap-4 sm:grid-cols-2"><label>SEO başlığı<input name="seo_title" defaultValue={settings.seo_title||"Ali Ulubaş • Minecraft Bedrock"} className={input}/></label><label>Anahtar kelimeler<input name="seo_keywords" defaultValue={settings.seo_keywords||"minecraft bedrock, bedrock modları, minecraft sunucuları"} className={input}/></label></div><label>SEO açıklaması<textarea name="seo_description" defaultValue={settings.seo_description||""} className={input} rows={3}/></label></div><label>Gelişmiş özel CSS<textarea name="custom_css" defaultValue={settings.custom_css||""} className={input} rows={5}/></label><button disabled={busy} className="admin-primary">Tüm Ayarları Kaydet</button></form>}{message&&<p className="mt-5 rounded-xl bg-violet-500/15 p-4 text-violet-300">{message}</p>}</section></div></div></main>}
